version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --experimental.localPlugins.traefik-token-auth.modulename=github.com/0xanonymeow/traefik-token-auth
      # - --experimental.plugins.traefik-token-auth.modulename=github.com/0xanonymeow/traefik-token-auth
      # - --experimental.plugins.traefik-token-auth.version=v0.1.0
      - --providers.docker=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --log.level=debug
      - --accesslog=true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.traefik.yml:/plugins-local/src/github.com/0xanonymeow/traefik-token-auth/.traefik.yml
      - ./plugin.go:/plugins-local/src/github.com/0xanonymeow/traefik-token-auth/plugin.go
      - ./vendor:/plugins-local/src/github.com/0xanonymeow/traefik-token-auth/vendor
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.tokenAuth.plugin.traefik-token-auth.headerField=X-Api-Token
      - traefik.http.middlewares.tokenAuth.plugin.traefik-token-auth.removeHeader=true
      - traefik.http.middlewares.tokenAuth.plugin.traefik-token-auth.algorithm=sha256
      - traefik.http.middlewares.tokenAuth.plugin.traefik-token-auth.hashedToken=d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
  whoami:
    image: whoami
    build:
      context: ../whoami
      dockerfile: Dockerfile
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=PathPrefix(`/`)
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.middlewares=tokenAuth@docker